#On utilisera ces paramètres pour la pipeline de Pytorch
image_size: (128, 128)
data_dir: data
train_dir: "C:/Users/thoma/OneDrive/Desktop/Centrale/3A/Spé info/SID/Méthodo/Projet/ds-project/data/01_raw/training"
val_dir: "C:/Users/thoma/OneDrive/Desktop/Centrale/3A/Spé info/SID/Méthodo/Projet/ds-project/data/01_raw/validation"
batch_size: 2
num_epochs: 20